object PluginCoordinates {
    const val ID = "com.github.chantsune.kotlin.gradle.template.plugin"
    const val GROUP = "com.github.chantsune.kotlin.gradle"
    const val VERSION = "1.0.0"
    const val IMPLEMENTATION_CLASS = "com.github.chantsune.kotlin.gradle.template.plugin.LicenseToolsPlusPlugin"
}

object PluginBundle {
    const val VCS = "https://github.com/ChanTsune/LicenseToolsPluginExtension"
    const val WEBSITE = "https://github.com/ChanTsune/LicenseToolsPluginExtension"
    const val DESCRIPTION = "Edit the yaml file generated by the Cookpad License Tools plugin"
    const val DISPLAY_NAME = "License Tools plugin Extension"
    val TAGS = listOf(
        "plugin",
        "gradle",
        "license"
    )
}

